### ISSUE TITLE
Exception in plugin `Gist Snippet (1.1.0)

### ISSUE THREAD

**Issue by tobiashochguertel** [chuntungho/gist-snippet#14]
The plugin throws the following exception:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.chuntung.plugin.gistsnippet.action.InsertAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.chuntung.plugin.gistsnippet]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

Information about IntelliJ and other Plugins:

```
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Tobias Hochgürtel
Subscription is active until January 30, 2025.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 12288M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  editor.minimap.enabled=true
  terminal.new.ui=true
Non-Bundled Plugins:
  hunspell (241.14494.251)
  dev.pnbarx.idea.treecolor (1.2.2)
  com.bluewaitor.tsReact (1.4.0)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  org.plugin.dot.id (1.5.3)
  com.intellij.remoteControl (241.14494.150)
  com.redhat.devtools.intellij.telemetry (1.1.0.52)
  org.jetbrains.plugins.go-template (241.14494.150)
  com.intellij.properties.bundle.editor (241.14494.150)
  com.andrey4623.rainbowcsv (2.0.2)
  com.jetbrains.edu (2024.3-2024.1-455)
  com.jinsihou.react.snippets (1.1.1)
  com.samvtran.plugins.macosforallkeymap (2.0.0)
  com.jetbrains.space (241.14494.150)
  com.steve.plugins.autoscroll (1.1)
  com.intellij.apacheConfig (241.14494.240)
  org.intellij.plugins.hcl (241.14494.150)
  com.karateca.jstoolbox (1.10)
  MultiHighlight (3.1.0)
  com.paperetto.dash (3.3)
  com.github.nhat-phan.codecleaner (2019.2.1)
  freeriders.mag.Modular-Architecture-Generator (0.1.2-SNAPSHOT)
  com.tabnine.TabNine (1.71.0)
  name.kropp.intellij.makefile (241.14494.150)
  com.github.jonathanlocke.intellij.easymapmac (1.0.5)
  com.intellij.guice (241.14494.158)
  com.chainstaysoftware.assertions2assertj (1.0.09)
  com.adgainai.springbooturlfullpath (1.0.3)
  gherkin (241.14494.150)
  DevKit (241.14494.247)
  com.github.rmatafonov.cucumber-scenarios-indexer (1.1.0)
  String Manipulation (9.12.0)
  com.intellij.wiremock (241.14494.150)
  net.ashald.envfile (3.4.2)
  io.conceptive.quarkus-intellij-plugin (1.3.2)
  MavenRunHelper (4.27.1-IJ2022.2)
  Groovy Console Plugin (0.1.5)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  com.chuntung.plugin.gistsnippet (1.1.0)
  com.github.yunabraska.githubworkflowplugin (3.2.1)
  com.intellij.commander (241.14494.158)
  org.asciidoctor.intellij.asciidoc (0.41.13)
  com.intellij.aqua (241.14494.241)
  awesome.console (0.1337.12)
  com.lukasbach.intellij.snippets.typescriptreact (1.0.9)
  com.intellij.plugins.macoskeymap (241.13688.16)
  LiveTemplatePreview (0.3)
  io.github.fstaudt.helm (0.8.2)
  com.intellij.ml.llm (241.14494.240)
  com.jetbrains.plugins.ini4idea (241.14494.240)
  com.mallowigi (95.0.0)
  com.yujunyang.intellij.plugin.sonar (0.2.2)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
  com.haulmont.rcb (241.14494.140)
  com.dmarcotte.handlebars (241.14494.150)
  kemoke.net.cssmodule (1.1)
  com.github.lppedd.idea-return-highlighter (0.8.3)
  com.intellij.lang.jsgraphql (241.14494.150)
  mdx.js (241.14494.140)
  io.plugin.tsnode (2022.11.14-1)
  JSTestDriver Plugin (202.5)
  com.haulmont.jpab (241.14494.158)
  com.github.copilot (1.5.1.5285)
  org.sonarlint.idea (10.4.2.78113)
  com.intellij.tide (241.14494.251)
  com.github.bjansen.intellij.pebble (v0.11.0)
  com.intellij.bigdatatools.core (241.14494.240)
  com.intellij.bigdatatools.kafka (241.14494.158)
  zielu.gittoolbox (500.2.3+233)
  io.jetclient (2024.1.5-241)
  izhangzhihao.rainbow.brackets (2024.2.2-241)
  com.clutcher.comments_highlighter (2024.1.13)
  net.labymod.intellij.singlehotswap (2.6)
  LivePlugin (0.8.6 beta)
  ru.adelf.idea.dotenv (2024.1)
  com.jetbrains.packagesearch.intellij-plugin (241.0.8)
  dev.turingcomplete.intellijdevelopertoolsplugins (4.1.1)
  org.mapstruct.intellij (1.6.1)
Kotlin: 241.14494.240-IJ
```

**Comment by chuntungho** [comment]
Fixed
