### ISSUE TITLE
Failed to connect to GitHub account

### ISSUE THREAD

**Issue by IngCharly** [chuntungho/gist-snippet#9]
There is an error when trying to connect to the GitHub account and it does not delete the account when reinstalling the plugin.

org.jetbrains.plugins.github.exceptions.GithubMissingTokenException: Missing access token for account

**Comment by chuntungho** [comment]
GitHub Account is managed by GitHub plugin, you can delete it in "File | Settings | Version Control | GitHub".

**Comment by TerryLiu** [comment]
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:403)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GitHub.setMyself(GitHub.java:569)
	at org.kohsuke.github.GitHub.access$000(GitHub.java:61)
	at org.kohsuke.github.GitHub$LoginLoadingUserAuthorizationProvider.getLogin(GitHub.java:176)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:144)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:504)
	at com.chuntung.plugin.gistsnippet.service.GistSnippetService.lambda$queryOwnGist$1(GistSnippetService.java:46)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at com.chuntung.plugin.gistsnippet.service.GistSnippetService.queryOwnGist(GistSnippetService.java:44)
	at com.chuntung.plugin.gistsnippet.view.InsertGistDialog$7.run(InsertGistDialog.java:440)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
![WX20221107-163353](https://user-images.githubusercontent.com/3073134/200263104-b734f8d3-162b-4993-989e-ee3464a6c325.png)

**Comment by chuntungho** [comment]
> java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:403) at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355) at org.kohsuke.github.Requester.fetch(Requester.java:76) at org.kohsuke.github.GitHub.setMyself(GitHub.java:569) at org.kohsuke.github.GitHub.access$000(GitHub.java:61) at org.kohsuke.github.GitHub$LoginLoadingUserAuthorizationProvider.getLogin(GitHub.java:176) at org.kohsuke.github.GitHub.(GitHub.java:144) at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:504) at com.chuntung.plugin.gistsnippet.service.GistSnippetService.lambda$queryOwnGist$1(GistSnippetService.java:46) at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330) at com.chuntung.plugin.gistsnippet.service.GistSnippetService.queryOwnGist(GistSnippetService.java:44) at com.chuntung.plugin.gistsnippet.view.InsertGistDialog$7.run(InsertGistDialog.java:440) at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665) at java.base/java.lang.Thread.run(Thread.java:834) ![WX20221107-163353](https://user-images.githubusercontent.com/3073134/200263104-b734f8d3-162b-4993-989e-ee3464a6c325.png)

Which IDE version did you use?
